### ISSUE TITLE
Will Not Load

### ISSUE THREAD

**Issue by Drakma** [Axieum/PedestalCrafting#1]
I can't get any pack to load with this mod.  I have tried multiple times.

https://pastebin.com/7HeAATZ0

    Minecraft Version: 1.12.2
    Java Version: 1.8.0_131, Oracle Corporation
    Forge 14.23.4.2727

**Comment by Axieum** [comment]
Thank you for the report, I'm currently working to fix this. I believe it is due to me forgetting to tell my mod to load _after_ The One Probe. Expect this to be fixed in the next update!

**Comment by Axieum** [comment]
This issue is fixed in the latest release (https://github.com/Axieum/PedestalCrafting/releases/tag/v1.0.1).

Thank you for the report!

**Comment by darkphan** [comment]
This still happens if you do have The One Probe installed.

**Comment by Drakma** [comment]
For what it's worth if pedestal and craft tweaker are the only mods installed in the pack it will not load and this error still occurs.

**Comment by Drakma** [comment]
Just came back to say I "just" got it working.  It was my bad.  The mod hadn't updated.  

Looks great!

**Comment by Axieum** [comment]
That's great to hear! I was honestly scratching my head as to why it wouldn't work still.

**Comment by darkphan** [comment]
The problem is the mod has a dependency on The One Probe and crashes if TOP is not installed. Not all modpack devs like to use TOP :/

**Comment by Axieum** [comment]
Thanks for the heads up! Fixed in version `1.0.2`.
